# Generated by Django 3.2.5 on 2021-08-05 11:24

import apps.word.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordWordlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.TextField(unique=True)),
                ('wordlist_id', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'word_wordlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', apps.word.models.DBForerinkey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='word.wordwordlist', to_field='word_id', unique=True)),
                ('spell', models.TextField(unique=True)),
                ('pos', models.TextField(blank=True, null=True)),
                ('cn_etym', models.TextField(blank=True, null=True)),
                ('en_etym', models.TextField(blank=True, null=True)),
                ('sentence', models.TextField(blank=True, null=True)),
                ('phonetic', models.TextField(blank=True, null=True)),
                ('word_forms', models.TextField(blank=True, null=True)),
                ('audio_sources', models.TextField(blank=True, null=True)),
                ('updated', models.IntegerField(blank=True, null=True)),
                ('raw', models.TextField(blank=True, null=True)),
                ('parsed', models.IntegerField()),
            ],
            options={
                'db_table': 'word',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', apps.word.models.DBForerinkey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='word.wordwordlist', to_field='wordlist_id', unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('create_time', models.DateField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wordlist',
                'managed': False,
            },
        ),
    ]
